name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - run: pnpm install

      - name: Run tests
        env:
          NEON_URL: ${{ secrets.NEON_URL }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SERVER_PORT: 3000

        run: |
          sudo apt-get update && sudo apt-get install -y redis-server
          redis-server --daemonize yes
          pnpm clean-db
          pnpm clean-redis
          pnpm test
